[package]
name = "rabbit"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
reqwest = "0.12.18"
serde_toml = "0.0.1"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.8.22"
